//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiaoVien
    {
        public int MAGV { get; set; }
        public string HOTEN { get; set; }
        public string TEN { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public byte[] HINHANH { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MaTD { get; set; }
        public Nullable<int> MaCV { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    }
}
